# Generated by Django 3.0.5 on 2020-05-03 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255)),
                ('stage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255)),
                ('fb_name', models.CharField(max_length=255)),
                ('fb_gender', models.CharField(max_length=255)),
                ('fb_url', models.CharField(max_length=255)),
                ('mask_avail', models.CharField(max_length=10)),
                ('mask_price', models.CharField(max_length=255)),
                ('sanitizer_avail', models.CharField(max_length=10)),
                ('sanitizer_price', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('locality', models.TextField()),
                ('pincode', models.CharField(max_length=255)),
                ('contact', models.CharField(default='not provided', max_length=12)),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('registration_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_open', models.CharField(max_length=10)),
                ('mask_avail', models.CharField(max_length=10)),
                ('sanitizer_avail', models.CharField(max_length=10)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_time', models.TimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='mask.RegisteredPerson')),
            ],
        ),
    ]
